### ISSUE TITLE
Error 'WEBPACK_MANIFEST_PATH'

### ISSUE THREAD

**Issue by koorukuroo** [sloria/cookiecutter-flask#189]
There is a issue for the update 0.13.0 (06/25/2017).

`RuntimeError: Flask-Webpack requires 'WEBPACK_MANIFEST_PATH' to be set and it must point to a valid json file.`

**Comment by cheevahagadog** [comment]
I've had the same problem

**Comment by Deathnerd** [comment]
Same here. I feel as though I'm missing a step in setting things up. Is there some command I have to run to make Webpack generate its `manifest.json`? I'm pretty new to Webpack to be honest

**Comment by cheevahagadog** [comment]
I was able to get it to work yesterday. I updated my npm: `npm install npm@latest -g` and then reran the `npm install`. It still wasn't working, so I commented out the place in app.py where it loads webpack. Somehow at that point it compiled the `manifest.json`. Then I uncommented the webpack load in the app.py script and it was up and running. Sorry for the enigmatic explanation - I'm still not sure why it compiled the manifest.json at that point.

**Comment by judy2k** [comment]
I worked it out!

You need to run `npm run-script build` to build the assets and manifest for the first time. After that, Flask will run happily.

It looks like you can also run `npm run-script start` to simultaneously run webpack (to recompile assets while you're developing) and Flask simultaneously.

**Comment by dan-fahey** [comment]
@judy2k, I had to run `npm install` before building the package 👍

**Comment by dan-fahey** [comment]
I had to run `npm install` before `npm run-script build` and use `npm run-script start` to get the whole thing running.

**Comment by Steven4294** [comment]
when i attempt to run the build script I get

```
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alfredpetteruti/Desktop/myflaskapp/webpack.config.js:7:27)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myflaskapp@1.0.0 build: `NODE_ENV=production webpack --progress --colors -p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myflaskapp@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alfredpetteruti/.npm/_logs/2017-10-24T22_56_46_024Z-debug.log
```

**Comment by mridubhatnagar** [comment]
Having the same issue. And yet to come up to any solution.

**Comment by r03** [comment]
I had the same error, but I didn't run the migrations yet. After that it worked fine.

      flask db init                                                                                                                                                                            
      flask db migrate                                                                                                                                                                         
      flask db upgrade                                                                                                                                                                         
      npm start

**Comment by taurus1211** [comment]
??
