### ISSUE TITLE
npm start throwing 'weird error 8'

### ISSUE THREAD

**Issue by Double-O-ren** [sloria/cookiecutter-flask#213]
I followed the commands to bootstrap the env. 
I get the following error when I run 
$ npm install

> deja-vous@1.0.0 start /home/ec2-user/dv/deja-vous
> ./node_modules/.bin/concurrently -n "WEBPACK,FLASK" -c "bgBlue.bold,bgMagenta.bold" "npm run webpack-dev-server" "npm run flask-server"

/home/ec2-user/dv/deja-vous/node_modules/concurrently/src/main.js:230
          spawnOpts.env = Object.assign({FORCE_COLOR: supportsColor.level}, pr
                                 ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at /home/ec2-user/dv/deja-vous/node_modules/concurrently/src/main.js:230:34
    at arrayMap (/home/ec2-user/dv/deja-vous/node_modules/concurrently/node_modules/lodash/lodash.js:660:23)
    at Function.map (/home/ec2-user/dv/deja-vous/node_modules/concurrently/node_modules/lodash/lodash.js:9571:14)
    at run (/home/ec2-user/dv/deja-vous/node_modules/concurrently/src/main.js:221:22)
    at main (/home/ec2-user/dv/deja-vous/node_modules/concurrently/src/main.js:72:5)
    at Object.<anonymous> (/home/ec2-user/dv/deja-vous/node_modules/concurrently/src/main.js:508:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0

How can I fix this? 
Thanks!

**Comment by Double-O-ren** [comment]
SOLVED: 
`npm install -g concurrently'
`apt-get install nodejs-legacy`
