### ISSUE TITLE
Exception during login

### ISSUE THREAD

**Issue by sbhtw** [sloria/cookiecutter-flask#82]
With latest PR #80 I can register new users, but I get an error "TypeError: string argument without an encoding" (trace see below) when logging in.

* Python 3.4.3
* PostgreSQL 9.5.4
* SQLAlchemy 1.0.12
* Flask-SQLAlchemy 2.1

Error does **not** occur when I use SQLite as database.

(Note: I get login to work by reverting #80 by changing `password = Column(db.Binary(128), nullable=True)` back to `change  password = Column(db.String(128), nullable=True)` in conjunction with updated `set_password()` implementation as suggested by @smewp [in a comment to #80](https://github.com/sloria/cookiecutter-flask/pull/80#issuecomment-252633083). But as @Cabalist pointed out in the same thread, this is rather a workaround than a solution.)

```
Traceback (most recent call last):
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/simrech/backend2/simrech/public/views.py", line 26, in home
    if form.validate_on_submit():
  File "/simrech/backend2/venv/lib/python3.4/site-packages/flask_wtf/form.py", line 166, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/simrech/backend2/simrech/public/forms.py", line 27, in validate
    self.user = User.query.filter_by(username=self.username.data).first()
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 184, in reraise
    raise value
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 71, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 428, in _instance
    loaded_instance, populate_existing, populators)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 486, in _populate_full
    dict_[key] = getter(row)
  File "/simrech/backend2/venv/lib/python3.4/site-packages/sqlalchemy/sql/sqltypes.py", line 859, in process
    value = bytes(value)
TypeError: string argument without an encoding
```

**Comment by sbhtw** [comment]
This can be closed: `flask db migrate` didn't catch the changed field type.

I rebuild my migrations, and needed to change

```python
sa.Column('password', sa.String(length=128), nullable=True)
```

to

```python
sa.Column('password', sa.Binary(), nullable=True)
```

Sorry for any confusion!
